#pragma once
#include "DuplicateDeclarationException.h"
#include "ParseConstException.h"
#include "UndeclaredVariableException.h"
#include "UnexpectedTokenExcepion.h"
#include "WrongExprException.h"
#include "WrongStatementException.h"
#include "UnknownTypeException.h"
#include "UnexpectedTopLevelDeclaration.h"